# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_HELLOREQUEST = descriptor.Descriptor(
  name='HelloRequest',
  full_name='protobuf.socketrpc.HelloRequest',
  filename='hello_world.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='my_name', full_name='protobuf.socketrpc.HelloRequest.my_name', index=0,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_HELLORESPONSE = descriptor.Descriptor(
  name='HelloResponse',
  full_name='protobuf.socketrpc.HelloResponse',
  filename='hello_world.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hello_world', full_name='protobuf.socketrpc.HelloResponse.hello_world', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)



class HelloRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HELLOREQUEST

class HelloResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HELLORESPONSE


_HELLOWORLDSERVICE = descriptor.ServiceDescriptor(
  name='HelloWorldService',
  full_name='protobuf.socketrpc.HelloWorldService',
  index=0,
  options=None,
  methods=[
  descriptor.MethodDescriptor(
    name='HelloWorld',
    full_name='protobuf.socketrpc.HelloWorldService.HelloWorld',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLORESPONSE,
    options=None,
  ),
])

class HelloWorldService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _HELLOWORLDSERVICE
class HelloWorldService_Stub(HelloWorldService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _HELLOWORLDSERVICE

