# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_TIMEREQUEST = descriptor.Descriptor(
  name='TimeRequest',
  full_name='protobuf.socketrpc.TimeRequest',
  filename='time.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TIMERESPONSE = descriptor.Descriptor(
  name='TimeResponse',
  full_name='protobuf.socketrpc.TimeResponse',
  filename='time.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='str_time', full_name='protobuf.socketrpc.TimeResponse.str_time', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)



class TimeRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TIMEREQUEST

class TimeResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TIMERESPONSE


_TIMESERVICE = descriptor.ServiceDescriptor(
  name='TimeService',
  full_name='protobuf.socketrpc.TimeService',
  index=0,
  options=None,
  methods=[
  descriptor.MethodDescriptor(
    name='getTime',
    full_name='protobuf.socketrpc.TimeService.getTime',
    index=0,
    containing_service=None,
    input_type=_TIMEREQUEST,
    output_type=_TIMERESPONSE,
    options=None,
  ),
])

class TimeService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _TIMESERVICE
class TimeService_Stub(TimeService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _TIMESERVICE

