#!/usr/bin/python
# Copyright (c) 2009 Las Cumbres Observatory (www.lcogt.net)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='hello_world.proto',
  package='protobuf.socketrpc',
  serialized_pb='\n\x11hello_world.proto\x12\x12protobuf.socketrpc\"\x1f\n\x0cHelloRequest\x12\x0f\n\x07my_name\x18\x02 \x02(\t\"$\n\rHelloResponse\x12\x13\n\x0bhello_world\x18\x01 \x02(\t2f\n\x11HelloWorldService\x12Q\n\nHelloWorld\x12 .protobuf.socketrpc.HelloRequest\x1a!.protobuf.socketrpc.HelloResponseB4\n,com.googlecode.protobuf.socketrpc.helloworld\x88\x01\x01\x90\x01\x01')




_HELLOREQUEST = descriptor.Descriptor(
  name='HelloRequest',
  full_name='protobuf.socketrpc.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='my_name', full_name='protobuf.socketrpc.HelloRequest.my_name', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=41,
  serialized_end=72,
)


_HELLORESPONSE = descriptor.Descriptor(
  name='HelloResponse',
  full_name='protobuf.socketrpc.HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hello_world', full_name='protobuf.socketrpc.HelloResponse.hello_world', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=74,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE

class HelloRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HELLOREQUEST
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.HelloRequest)

class HelloResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HELLORESPONSE
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.HelloResponse)


_HELLOWORLDSERVICE = descriptor.ServiceDescriptor(
  name='HelloWorldService',
  full_name='protobuf.socketrpc.HelloWorldService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=112,
  serialized_end=214,
  methods=[
  descriptor.MethodDescriptor(
    name='HelloWorld',
    full_name='protobuf.socketrpc.HelloWorldService.HelloWorld',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLORESPONSE,
    options=None,
  ),
])

class HelloWorldService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _HELLOWORLDSERVICE
class HelloWorldService_Stub(HelloWorldService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _HELLOWORLDSERVICE

# @@protoc_insertion_point(module_scope)
