// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.googlecode.protobuf.socketrpc;

public final class TestProtos {
  private TestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {}
    
    private static final Request defaultInstance = new Request();
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.socketrpc.TestProtos.internal_static_protobuf_socketrpc_Request_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.socketrpc.TestProtos.internal_static_protobuf_socketrpc_Request_fieldAccessorTable;
    }
    
    // required string str_data = 1;
    private boolean hasStrData;
    private java.lang.String strData_ = "";
    public boolean hasStrData() { return hasStrData; }
    public java.lang.String getStrData() { return strData_; }
    
    public static com.googlecode.protobuf.socketrpc.TestProtos.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.googlecode.protobuf.socketrpc.TestProtos.Request prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.googlecode.protobuf.socketrpc.TestProtos.Request.newBuilder()
      private Builder() {}
      
      com.googlecode.protobuf.socketrpc.TestProtos.Request result = new com.googlecode.protobuf.socketrpc.TestProtos.Request();
      
      @Override
      protected com.googlecode.protobuf.socketrpc.TestProtos.Request internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.googlecode.protobuf.socketrpc.TestProtos.Request();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.socketrpc.TestProtos.Request.getDescriptor();
      }
      
      public com.googlecode.protobuf.socketrpc.TestProtos.Request getDefaultInstanceForType() {
        return com.googlecode.protobuf.socketrpc.TestProtos.Request.getDefaultInstance();
      }
      
      public com.googlecode.protobuf.socketrpc.TestProtos.Request build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.googlecode.protobuf.socketrpc.TestProtos.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.protobuf.socketrpc.TestProtos.Request buildPartial() {
        com.googlecode.protobuf.socketrpc.TestProtos.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string str_data = 1;
      public boolean hasStrData() {
        return result.hasStrData();
      }
      public java.lang.String getStrData() {
        return result.getStrData();
      }
      public Builder setStrData(java.lang.String value) {
        result.hasStrData = true;
        result.strData_ = value;
        return this;
      }
      public Builder clearStrData() {
        result.hasStrData = false;
        result.strData_ = "";
        return this;
      }
    }
    
    static {
      com.googlecode.protobuf.socketrpc.TestProtos.getDescriptor();
    }
  }
  
  public static final class Response extends
      com.google.protobuf.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {}
    
    private static final Response defaultInstance = new Response();
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.socketrpc.TestProtos.internal_static_protobuf_socketrpc_Response_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.socketrpc.TestProtos.internal_static_protobuf_socketrpc_Response_fieldAccessorTable;
    }
    
    // required string str_data = 1;
    private boolean hasStrData;
    private java.lang.String strData_ = "";
    public boolean hasStrData() { return hasStrData; }
    public java.lang.String getStrData() { return strData_; }
    
    public static com.googlecode.protobuf.socketrpc.TestProtos.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.socketrpc.TestProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.googlecode.protobuf.socketrpc.TestProtos.Response prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.googlecode.protobuf.socketrpc.TestProtos.Response.newBuilder()
      private Builder() {}
      
      com.googlecode.protobuf.socketrpc.TestProtos.Response result = new com.googlecode.protobuf.socketrpc.TestProtos.Response();
      
      @Override
      protected com.googlecode.protobuf.socketrpc.TestProtos.Response internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.googlecode.protobuf.socketrpc.TestProtos.Response();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.socketrpc.TestProtos.Response.getDescriptor();
      }
      
      public com.googlecode.protobuf.socketrpc.TestProtos.Response getDefaultInstanceForType() {
        return com.googlecode.protobuf.socketrpc.TestProtos.Response.getDefaultInstance();
      }
      
      public com.googlecode.protobuf.socketrpc.TestProtos.Response build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.googlecode.protobuf.socketrpc.TestProtos.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.protobuf.socketrpc.TestProtos.Response buildPartial() {
        com.googlecode.protobuf.socketrpc.TestProtos.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string str_data = 1;
      public boolean hasStrData() {
        return result.hasStrData();
      }
      public java.lang.String getStrData() {
        return result.getStrData();
      }
      public Builder setStrData(java.lang.String value) {
        result.hasStrData = true;
        result.strData_ = value;
        return this;
      }
      public Builder clearStrData() {
        result.hasStrData = false;
        result.strData_ = "";
        return this;
      }
    }
    
    static {
      com.googlecode.protobuf.socketrpc.TestProtos.getDescriptor();
    }
  }
  
  public static abstract class TestService
      implements com.google.protobuf.Service {
    public abstract void testMethod(
        com.google.protobuf.RpcController controller,
        com.googlecode.protobuf.socketrpc.TestProtos.Request request,
        com.google.protobuf.RpcCallback<com.googlecode.protobuf.socketrpc.TestProtos.Response> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.googlecode.protobuf.socketrpc.TestProtos.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.testMethod(controller, (com.googlecode.protobuf.socketrpc.TestProtos.Request)request,
            com.google.protobuf.RpcUtil.<com.googlecode.protobuf.socketrpc.TestProtos.Response>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.RuntimeException("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.googlecode.protobuf.socketrpc.TestProtos.Request.getDefaultInstance();
        default:
          throw new java.lang.RuntimeException("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.googlecode.protobuf.socketrpc.TestProtos.Response.getDefaultInstance();
        default:
          throw new java.lang.RuntimeException("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends com.googlecode.protobuf.socketrpc.TestProtos.TestService {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public void testMethod(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.socketrpc.TestProtos.Request request,
          com.google.protobuf.RpcCallback<com.googlecode.protobuf.socketrpc.TestProtos.Response> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.googlecode.protobuf.socketrpc.TestProtos.Response.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.googlecode.protobuf.socketrpc.TestProtos.Response.class,
            com.googlecode.protobuf.socketrpc.TestProtos.Response.getDefaultInstance()));
      }
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_socketrpc_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_socketrpc_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_socketrpc_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_socketrpc_Response_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n5src/test/com/googlecode/protobuf/socke" +
      "trpc/test.proto\022\022protobuf.socketrpc\"\033\n\007R" +
      "equest\022\020\n\010str_data\030\001 \002(\t\"\034\n\010Response\022\020\n\010" +
      "str_data\030\001 \002(\t2V\n\013TestService\022G\n\nTestMet" +
      "hod\022\033.protobuf.socketrpc.Request\032\034.proto" +
      "buf.socketrpc.ResponseB/\n!com.googlecode" +
      ".protobuf.socketrpcB\nTestProtos";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_socketrpc_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_socketrpc_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_socketrpc_Request_descriptor,
              new java.lang.String[] { "StrData", },
              com.googlecode.protobuf.socketrpc.TestProtos.Request.class,
              com.googlecode.protobuf.socketrpc.TestProtos.Request.Builder.class);
          internal_static_protobuf_socketrpc_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuf_socketrpc_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_socketrpc_Response_descriptor,
              new java.lang.String[] { "StrData", },
              com.googlecode.protobuf.socketrpc.TestProtos.Response.class,
              com.googlecode.protobuf.socketrpc.TestProtos.Response.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
